name = "traffic-logger-local"
main = "src/app/index.ts"
compatibility_date = "2022-07-22"

[env.gateway]
name = "traffic-logger-gateway"
main = "src/gateway/index.ts"
routes = ["do.omrilotan.com/*", "omrilotan.com", "omrilotan.com/*"]
services = [
	{ binding = "MAIN", service = "traffic-logger-main", environment = "production" },
	{ binding = "CANARY", service = "traffic-logger-canary", environment = "production" }
]
kv_namespaces = [
	{ binding = "ROLLOUT", id = "309b38e6127b48eb86ff9a58e715ac15" }
]
ROLLOUT_KEY = "traffic-logger-canary"
ROLLOUT_HEADER = "force-rollout"

[env.canary]
name = "traffic-logger-canary"

[[env.canary.unsafe.bindings]]
type = "analytics_engine"
name = "TRAFFIC_ANALYTICS"
dataset = "TRAFFIC_ANALYTICS"

[env.canary.vars]
VARIATION = "canary"
SEND_ANALYTICS = true
SEND_LOGS = true

[env.main]
name = "traffic-logger-main"
routes = [
	{ pattern = "*danisilas.com/*", zone_id = "d9470a8d1d50c3187550f48efa23e92f" }
]

[[env.canary.unsafe.bindings]]
type = "analytics_engine"
name = "TRAFFIC_ANALYTICS"
dataset = "TRAFFIC_ANALYTICS"

[env.main.vars]
VARIATION = "main"
SEND_ANALYTICS = false
SEND_LOGS = true
