name = 'proxy'
main = 'src/index.ts'
compatibility_date = '2022-07-22'
routes = [
	{ pattern = 'gerbil.omrilotan.com', custom_domain = true },
	{ pattern = 'tv.omrilotan.com', custom_domain = true },
]

[vars]
PROXY_HOSTMAP = '{"tv.omrilotan.com":"goat-willing-partly.ngrok-free.app","gerbil.omrilotan.com":"lab-9sgd.onrender.com"}'