const dataCentreAutonomousSystemList = new Set<string>([
	"Aixit GmbH",
	"Alibaba",
	"Amazon.com",
	"Amazon",
	"DATACITY",
	"Digital Ocean",
	"DigitalOcean",
	"Flyservers S.A.",
	"GoDaddy.com, LLC",
	"Google Cloud",
	"GTHost",
	"Hetzner Online GmbH",
	"Hosteur SAS",
	"Hostwinds LLC.",
	"Intergrid Group Pty",
	"Internet Archive",
	"Ispconnected",
	"Limestone Networks",
	"Meverywhere sp. z o.o.",
	"Microsoft Azure",
	"Microsoft Corporation",
	"Oracle Cloud",
	"OVH SAS",
	"ServerMania",
	"Strato AG",
	"Tencent cloud computing",
	"Vivid Hosting",
	"Web Hosted Group Ltd",
]);

export const isDataCentreAutonomousSystem = (as: string): boolean =>
	dataCentreAutonomousSystemList.has(as);
